blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: https://github.com/MackJack023/GuardianStar/blob/main/SECURITY.md
    about: Please report sensitive vulnerabilities privately.
